monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [404, 405]
        nested:
            type: syslog
            level: notice
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
