# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    env(SHINAGE_SERVER_BASE_URL): "http://127.0.0.1:8001/api/v1/"
    env(SHINAGE_SERVER_RENDER_URL): "http://127.0.0.1:8001/presentations/"
    env(SHINAGE_SCREEN_GUID): "f5593517-9939-490d-9a5a-d0a73e9535c4"
    env(SHINAGE_REMOTE_TIMEOUT): "10000"
    env(CACHE_BASE_PATH): "/tmp/shinage_cache"

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Cache\LocalFileCache:
        arguments:
            $basePath: "%env(CACHE_BASE_PATH)%"

    App\ApiClient\ApiClientV1:
        arguments:
            #$remoteBaseUrl: "https://app-staging.shinage.org/api/v1/"
            $remoteBaseUrl: "%env(SHINAGE_SERVER_BASE_URL)%"
            #$screenGuid: "2614503e-2266-4158-b621-d94277f75507"
            $screenGuid: "%env(SHINAGE_SCREEN_GUID)%"
            $timeout: "%env(SHINAGE_REMOTE_TIMEOUT)%"

    App\ApiClient\RenderClient:
        arguments:
            $remoteBaseUrl: "%env(SHINAGE_SERVER_RENDER_URL)%"
            $screenGuid: "%env(SHINAGE_SCREEN_GUID)%"
            $timeout: "%env(SHINAGE_REMOTE_TIMEOUT)%"


    App\Controller\CurrentController:
        arguments:
            $remoteRenderBaseUrl: "%env(SHINAGE_SERVER_RENDER_URL)%"

